#!/usr/bin/env python3
"""
Exhibit Audit Script — Step 1.B1-a

Walks DoD_Budget_Documents/ for all .xlsx files, reads sheet names and header
rows (first 5 rows), groups by detected exhibit type, and emits a Markdown
report of unique (exhibit_type, sheet_pattern, header_signature) tuples.

Usage:
    python scripts/exhibit_audit.py
    python scripts/exhibit_audit.py --docs-dir /path/to/DoD_Budget_Documents
    python scripts/exhibit_audit.py --output docs/exhibit_audit_report.md

Requires downloaded budget files in DoD_Budget_Documents/ (see dod_budget_downloader.py).
"""

import argparse
import sys
from collections import defaultdict
from pathlib import Path

# Ensure project root is on the path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import openpyxl

from build_budget_db import _detect_exhibit_type


def _find_header_row(rows: list[tuple]) -> int | None:
    """Return the index of the row containing 'Account' (case-insensitive)."""
    for i, row in enumerate(rows[:10]):
        for cell in row:
            if cell and str(cell).strip().lower() == "account":
                return i
    return None


def _header_signature(headers: tuple) -> str:
    """Return a compact string summarizing header cells (non-None, max 6)."""
    non_null = [str(h).strip() for h in headers if h is not None and str(h).strip()]
    return " | ".join(non_null[:6])


def audit_documents(docs_dir: Path) -> dict[str, list[dict]]:
    """Walk docs_dir for .xlsx files and collect header signatures per exhibit type."""
    results: dict[str, list[dict]] = defaultdict(list)

    xlsx_files = sorted(docs_dir.rglob("*.xlsx"))
    if not xlsx_files:
        print(f"No .xlsx files found in {docs_dir}", file=sys.stderr)
        return results

    print(f"Scanning {len(xlsx_files)} .xlsx files...")

    for xlsx_path in xlsx_files:
        exhibit_type = _detect_exhibit_type(xlsx_path.name)
        rel_path = xlsx_path.relative_to(docs_dir)

        try:
            wb = openpyxl.load_workbook(str(xlsx_path), read_only=True, data_only=True)
        except Exception as exc:
            results[exhibit_type].append({
                "file": str(rel_path),
                "sheet": "N/A",
                "error": str(exc),
                "header_sig": "",
            })
            continue

        for sheet_name in wb.sheetnames:
            try:
                ws = wb[sheet_name]
                rows = [r for r in ws.iter_rows(max_row=10, values_only=True)]
            except Exception as exc:
                results[exhibit_type].append({
                    "file": str(rel_path),
                    "sheet": sheet_name,
                    "error": str(exc),
                    "header_sig": "",
                })
                continue

            header_idx = _find_header_row(rows)
            if header_idx is not None:
                sig = _header_signature(rows[header_idx])
            else:
                sig = _header_signature(rows[0]) if rows else "(empty)"

            results[exhibit_type].append({
                "file": str(rel_path),
                "sheet": sheet_name,
                "header_sig": sig,
                "error": None,
            })

        wb.close()

    return results


def _deduplicate(entries: list[dict]) -> list[dict]:
    """Return unique entries by (sheet, header_sig)."""
    seen: set[tuple] = set()
    unique = []
    for e in entries:
        key = (e["sheet"], e["header_sig"])
        if key not in seen:
            seen.add(key)
            unique.append(e)
    return unique


def generate_report(results: dict[str, list[dict]], docs_dir: Path) -> str:
    """Generate Markdown audit report."""
    total_files = sum(len(v) for v in results.values())
    lines = [
        "# Exhibit Type Audit Report",
        "",
        f"Generated by `scripts/exhibit_audit.py` — scanned `{docs_dir}`",
        f"Total sheets audited: {total_files}",
        "",
        "---",
        "",
    ]

    for exhibit_type in sorted(results.keys()):
        entries = results[exhibit_type]
        unique = _deduplicate(entries)
        lines.append(f"## {exhibit_type.upper()} ({len(entries)} sheets, {len(unique)} unique layouts)")
        lines.append("")
        lines.append("| Sheet Name | Header Signature | File Example |")
        lines.append("|------------|-----------------|--------------|")
        for e in unique[:20]:  # cap at 20 per exhibit type
            sheet = e["sheet"] or ""
            sig = e["header_sig"] or "(no header found)"
            file_ex = e["file"] or ""
            if e.get("error"):
                sig = f"ERROR: {e['error'][:60]}"
            lines.append(f"| `{sheet}` | {sig} | `{file_ex}` |")
        if len(unique) > 20:
            lines.append(f"| _(+{len(unique) - 20} more)_ | | |")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Catalog Coverage Summary")
    lines.append("")
    lines.append("| Exhibit Type | Sheets Found | Status |")
    lines.append("|-------------|-------------|--------|")

    try:
        from exhibit_catalog import EXHIBIT_CATALOG
        cataloged = set(EXHIBIT_CATALOG.keys())
    except ImportError:
        cataloged = set()

    all_types = set(results.keys())
    for et in sorted(all_types | cataloged):
        count = len(results.get(et, []))
        status = "✓ In catalog" if et in cataloged else "⚠ Not in catalog"
        lines.append(f"| `{et}` | {count} | {status} |")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Audit DoD budget exhibit types")
    parser.add_argument(
        "--docs-dir",
        type=Path,
        default=Path("DoD_Budget_Documents"),
        help="Path to downloaded budget documents (default: DoD_Budget_Documents/)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/exhibit_audit_report.md"),
        help="Output Markdown report path (default: docs/exhibit_audit_report.md)",
    )
    args = parser.parse_args()

    if not args.docs_dir.exists():
        print(f"ERROR: Documents directory not found: {args.docs_dir}", file=sys.stderr)
        print("Run dod_budget_downloader.py first to download budget files.", file=sys.stderr)
        sys.exit(1)

    results = audit_documents(args.docs_dir)
    report = generate_report(results, args.docs_dir)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report)
    print(f"Report written to {args.output}")

    # Also print summary to stdout
    total_sheets = sum(len(v) for v in results.values())
    print(f"\nSummary: {total_sheets} sheets across {len(results)} exhibit types")
    for et, entries in sorted(results.items()):
        print(f"  {et:8s}: {len(entries):4d} sheets")


if __name__ == "__main__":
    main()
